.\" Manpage for librarian.
.\" Contact mikee@saxicola.co.uk to correct errors or typos.
.TH man 3 "06 May 2018" "1.0" "librarian man page"
.SH NAME
librarian \- A library cataloguing system.
.SH SYNOPSIS
librarian
.SH DESCRIPTION
librarian is a book cataloguing system
.SH OPTIONS
The librarian does not take any options.
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
Mike Evans (mikee@saxicola.co.uk)

