char *s = N_("Hello World");
char *s = N_("PRINT _LIST");
char *s = N_("Q_UERY");
char *s = N_("THE LIBRARIAN");
char *s = N_("_ALL BOOKS");
char *s = N_("_LOANED BOOKS");
char *s = N_("_QUIT");
char *s = N_("_SCAN NEW");
char *s = N_("_SEARCH");
