#!/bin/sh
# Create po files for internationalisation
# see: http://faq.pygtk.org/index.py?file=faq22.002.htp&req=edit
mkdir po
intltool-extract --type=gettext/glade ui/librarian.glade
intltool-extract --type=gettext/glade ui/edit_book.glade
intltool-extract --type=gettext/glade ui/gui.glade
intltool-extract --type=gettext/glade ui/borrower_dialog.glade

xgettext -k_ -kN_ -o po/messages.pot *.py ui/*.*.h

mkdir -p locale/en_GB/LC_MESSAGES/
msgfmt po/en_GB.po -o locale/en_GB/LC_MESSAGES/librarian.mo

mkdir -p locale/cy/LC_MESSAGES/
msgfmt po/cy.po -o locale/cy/LC_MESSAGES/librarian.mo
